-- Moultrie Pickleball Association
-- Secure shared-data database with Supabase Auth + admin-only writes.
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.club_players (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'player' check (role in ('player','admin')),
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  player_a bigint not null constraint games_player_a_fkey references public.club_players(id) on delete cascade,
  player_b bigint not null constraint games_player_b_fkey references public.club_players(id) on delete cascade,
  score_a integer,
  score_b integer,
  created_at timestamptz not null default now(),
  constraint games_different_players check (player_a <> player_b),
  constraint games_score_a_nonnegative check (score_a is null or score_a >= 0),
  constraint games_score_b_nonnegative check (score_b is null or score_b >= 0)
);

create index if not exists games_player_a_idx on public.games(player_a);
create index if not exists games_player_b_idx on public.games(player_b);

-- New Auth users automatically receive a normal player profile.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'display_name',''), split_part(new.email,'@',1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Security helper. The role is stored in a protected table, not editable
-- through user metadata.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- Turn on RLS.
alter table public.profiles enable row level security;
alter table public.club_players enable row level security;
alter table public.games enable row level security;

-- Remove broad API grants, then give only authenticated users the operations
-- this app needs. service_role remains available to Supabase internally.
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.club_players from anon, authenticated;
revoke all on table public.games from anon, authenticated;

grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.club_players to authenticated;
grant select, insert, update, delete on public.games to authenticated;

-- Profiles: users can read their own profile; admins can read all profiles.
drop policy if exists "own profile read" on public.profiles;
create policy "own profile read"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "admins read profiles" on public.profiles;
create policy "admins read profiles"
on public.profiles for select
to authenticated
using ((select public.is_admin()));

-- Only admins can change profiles/roles.
drop policy if exists "admins update profiles" on public.profiles;
create policy "admins update profiles"
on public.profiles for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- Club roster: authenticated users can read; admins alone can write.
drop policy if exists "members read players" on public.club_players;
create policy "members read players"
on public.club_players for select
to authenticated
using (true);

drop policy if exists "admins insert players" on public.club_players;
create policy "admins insert players"
on public.club_players for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins update players" on public.club_players;
create policy "admins update players"
on public.club_players for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins delete players" on public.club_players;
create policy "admins delete players"
on public.club_players for delete
to authenticated
using ((select public.is_admin()));

-- Games: authenticated users can read; admins alone can create/edit/delete.
drop policy if exists "members read games" on public.games;
create policy "members read games"
on public.games for select
to authenticated
using (true);

drop policy if exists "admins insert games" on public.games;
create policy "admins insert games"
on public.games for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins update games" on public.games;
create policy "admins update games"
on public.games for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins delete games" on public.games;
create policy "admins delete games"
on public.games for delete
to authenticated
using ((select public.is_admin()));

-- Realtime updates across phones.
do $$
begin
  alter publication supabase_realtime add table public.club_players;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.games;
exception when duplicate_object then null;
end $$;

-- IMPORTANT:
-- After creating your first account in the app, replace YOUR_EMAIL below
-- with your email and run this ONE statement to make yourself the admin.
--
-- update public.profiles
-- set role = 'admin'
-- where id = (select id from auth.users where email = 'YOUR_EMAIL');
